### ISSUE TITLE
Simplify the CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [seariver520/prj-rev-bwfs-dasmoto#4]
There are several properties in the CSS which are shared by multiple selectors. It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. 

You did a great job simplifying for the h2 element properties. You can simplify the code further for several other properties. Consider the code

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
``` 

and remove the shared properties in the other selectors since this will apply them to all elements nested in the html tags.
