### ISSUE TITLE
Suggestion: Order the CSS selectors to reflect the order in the HTML

### ISSUE THREAD

**Issue by josephtkim** [seariver520/prj-rev-bwfs-dasmoto#5]
It is usually a good idea to order the selectors in your CSS to be similar to the order as the appear in the HTML code. This makes it easier to follow along the CSS code since it follows the structure of the HTML as well. It does not have to be perfectly in the order they appear, but it should make sense, and similar selectors should be grouped together. 

Here is how you might reorder the CSS

```css
html {
  font-family: Helvetica;
}

.header h1 {
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
}

h2 {
  font-family: Helvetica;
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes h2 {
  background-color: mediumspringgreen;
}

.frames h2{
  background-color: lightcoral;
}

.paint h2{
  background-color: skyblue;
}

b {
  font-family: Helvetica;
  font-weight: bold;
  color: blue;
}
```
